###
#
# @author Fluidity Ops
# @version 1.0.0
#
###

version: 2.1

orbs:
  airswap: airswap/assume-role@volatile
  aws-cli: airswap/aws-cli@volatile

references:
  container_config: &container_config
    docker:
      - image: circleci/node:12
    working_directory: ~/repo

  npm_cache_key: &npm_cache_key v4-dependencies-{{ checksum "package.json" }}
  npm_backup_cache_key: &npm_backup_cache_key v4-dependencies-

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *npm_cache_key
        - *npm_backup_cache_key

  install_missing_packages: &install_missing_packages
    run:
      command: |
        sudo apt-get install libusb-1.0-0-dev

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v4-repo-{{ .Branch }}-{{ .Revision }}
        - v4-repo-{{ .Branch }}
        - v4-repo

  build_and_deploy: &build_and_deploy
    <<: *container_config
    resource_class: large
    steps:
      - *restore_repo
      - checkout
      - *restore_node_modules
      - *install_missing_packages
      - run:
          name: yarn install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: *npm_cache_key
      - run:
          name: build minified files
          command: |
            echo "Building for $ENV / $STAGE in branch: $CIRCLE_BRANCH with domain $DOMAIN "
            echo "export REACT_APP_GIT_SHA1=$CIRCLE_SHA1" >> $BASH_ENV
            REACT_APP_SERVER_ENV=$ENV REACT_APP_ENVIRONMENT=$ENV ENV=$ENV GENERATE_SOURCEMAP=false CI=false yarn build # dont treat warnings as errors
      - aws-cli/install
      - airswap/assume-role:
          role-name: StaticSiteDeployer
      - persist_to_workspace:
          root: ~/repo
          paths: .

jobs:
  development:
    <<: *build_and_deploy
  production:
    <<: *build_and_deploy

workflows:
  build_test_deploy:
    jobs:
      - development:
          context: Development
          filters:
            branches:
              only:
                - develop
      - production:
          context: Production
          filters:
            branches:
              only:
                - master
